version: 2.1

jobs:
  liquibase-update:
    docker:
      - image: liquibase/liquibase:4.33-alpine
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install MySQL JDBC driver via Liquibase package manager
          command: |
            lpm add mysql --global
      - run:
          name: Run Liquibase update (password auth)
          command: |
            if [ -z "${RDS_ENDPOINT:-}" ]; then
              echo "RDS_ENDPOINT must be set in CircleCI project env vars" >&2
              exit 1
            fi
            if [ -z "${RDS_PASSWORD:-}" ]; then
              echo "RDS_PASSWORD must be set in CircleCI project env vars" >&2
              exit 1
            fi
            DB_NAME="${RDS_DB_NAME:-liquibaseapp}"
            USERNAME="${RDS_USERNAME:-username}"
            SSL_MODE="${SSL_MODE:-REQUIRED}"
            JDBC_URL="jdbc:mysql://${RDS_ENDPOINT}/${DB_NAME}?sslMode=${SSL_MODE}"
            liquibase \
              --url="$JDBC_URL" \
              --username="$USERNAME" \
              --password="$RDS_PASSWORD" \
              --changeLogFile=docker/files/liquibase/changelog/changelog-master.yaml \
              --log-level=info \
              update

workflows:
  liquibase:
    jobs:
      - liquibase-update:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/


